const NEAT_HP = {
  BIAS: {},
  WEIGHT: {},
  INIT: {},
  MUTATION: {},
  VALUE: {},
  MUTATION: {
    WEIGHTS: {}
  }
}

NEAT_HP.VALUE.min = -1;
NEAT_HP.VALUE.max = 1;

// NEAT_HP.BIAS.min = -0.05;
// NEAT_HP.BIAS.max = 0.05;

NEAT_HP.BIAS.min = -0.5;
NEAT_HP.BIAS.max = 0.5;

NEAT_HP.WEIGHT.min = -1;
NEAT_HP.WEIGHT.max = 1;

NEAT_HP.INIT.CONNECTION_CHANCE = 1;
NEAT_HP.INIT.CONNECTION_VAL = 0;

NEAT_HP.MUTATION.WEIGHTS.MIN = -1;
NEAT_HP.MUTATION.WEIGHTS.MAX = 1;
NEAT_HP.MUTATION.WEIGHTS.FIXED = true; 

NEAT_HP.MUTATION.NODE_CHANCE = 0.05; // 5% chance for new node